version: "3.9"

services:
  # =============================
  # INDEXER NODES (Elasticsearch / OpenSearch)
  # =============================
  indexer-1:
    image: wazuh/wazuh-indexer:4.13.1
    hostname: indexer-1
    environment:
      - node.name=indexer-1
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - cluster.initial_master_nodes=indexer-1,indexer-2
      - discovery.seed_hosts=indexer-1,indexer-2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./certs:/usr/share/wazuh-indexer/certs
      - indexer1_data:/var/lib/wazuh-indexer
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  indexer-2:
    image: wazuh/wazuh-indexer:4.13.1
    hostname: indexer-2
    environment:
      - node.name=indexer-2
      - cluster.name=wazuh-cluster
      - network.host=0.0.0.0
      - cluster.initial_master_nodes=indexer-1,indexer-2
      - discovery.seed_hosts=indexer-1,indexer-2
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./certs:/usr/share/wazuh-indexer/certs
      - indexer2_data:/var/lib/wazuh-indexer
    ports:
      - "9202:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # =============================
  # MANAGER NODES
  # =============================
  manager-1:
    image: wazuh/wazuh-manager:4.13.1
    hostname: manager-1
    environment:
      - INDEXER_URL=https://nginx:9200
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - ./certs:/etc/wazuh-manager/certs
      - manager1_data:/var/ossec/data
    ports:
      - "1515:1515"
      - "55000:55000"

  manager-2:
    image: wazuh/wazuh-manager:4.13.1
    hostname: manager-2
    environment:
      - INDEXER_URL=https://nginx:9200
      - FILEBEAT_SSL_VERIFICATION_MODE=none
    volumes:
      - ./certs:/etc/wazuh-manager/certs
      - manager2_data:/var/ossec/data
    ports:
      - "1516:1515"
      - "55001:55000"

  # =============================
  # DASHBOARD
  # =============================
  dashboard:
    image: wazuh/wazuh-dashboard:4.13.1
    hostname: dashboard
    depends_on:
      - nginx
    environment:
      - INDEXER_URL=https://nginx:9200
      - WAZUH_API_URL=https://nginx:55000
      - DASHBOARD_USERNAME=admin
      - DASHBOARD_PASSWORD=admin123
      - SSL_CERTIFICATE=/usr/share/wazuh-dashboard/certs/dashboard.pem
      - SSL_CERTIFICATE_KEY=/usr/share/wazuh-dashboard/certs/dashboard-key.pem
    volumes:
      - ./certs:/usr/share/wazuh-dashboard/certs
    ports:
      - "443:443"

  # =============================
  # NGINX REVERSE PROXY (HTTPS)
  # =============================
  nginx:
    image: nginx:stable
    hostname: nginx
    depends_on:
      - indexer-1
      - indexer-2
      - manager-1
      - manager-2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    ports:
      - "9200:9200"  # proxy cho indexer cluster
      - "55000:55000"  # proxy cho manager cluster

volumes:
  indexer1_data:
  indexer2_data:
  manager1_data:
  manager2_data:
