version: "3.8"

services:
  # =============================
  # INDEXER NODES (Elasticsearch / OpenSearch)
  # =============================
  indexer-1:
    image: wazuh/wazuh-indexer:4.13.1
    hostname: indexer-1.indexer
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./config/certs:/etc/wazuh-indexer/certs:rw
      - ./data/index1:/var/lib/wazuh-indexer
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - SYS_RESOURCE
    networks:
      - capstone-network

  indexer-2:
    image: wazuh/wazuh-indexer:4.13.1
    hostname: indexer-2.indexer
    restart: always
    environment:
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
    volumes:
      - ./config/certs:/etc/wazuh-indexer/certs:rw
      - ./data/index2:/var/lib/wazuh-indexer
    ports:
      - "9202:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - SYS_RESOURCE
    networks:
      - capstone-network       

  # =============================
  # MANAGER NODES
  # =============================
  manager-1:
    image: wazuh/wazuh-manager:4.13.1
    hostname: manager-1.server
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    cap_add:
      - SYS_RESOURCE
    environment:
     INDEXER_URL: https://nginx:9200
     INDEXER_USERNAME: ${INDEXER_USERNAME}
     INDEXER_PASSWORD: ${INDEXER_PASSWORD}
     FILEBEAT_SSL_VERIFICATION_MODE: full
     SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
     SSL_CERTIFICATE: /etc/ssl/manager-1-key.pem
     SSL_KEY: /etc/ssl/manager-1-key.key
     API_USERNAME: ${API_USERNAME}
     API_PASSWORD: ${API_PASSWORD}

    volumes:
      - ./config/certs:/etc/ssl:rw
      - ./data/manager1:/var/ossec/data
    ports:
      - "1515:1515"
      - "55000:55000"
    networks:
      - capstone-network

  manager-2:
    image: wazuh/wazuh-manager:4.13.1
    hostname: manager-2.server
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 655360
        hard: 655360
    cap_add:
      - SYS_RESOURCE
    environment:
     INDEXER_URL: https://nginx:9200
     INDEXER_USERNAME: ${INDEXER_USERNAME}
     INDEXER_PASSWORD: ${INDEXER_PASSWORD}
     FILEBEAT_SSL_VERIFICATION_MODE: full
     SSL_CERTIFICATE_AUTHORITIES: /etc/ssl/root-ca.pem
     SSL_CERTIFICATE: /etc/ssl/manager-2-key.pem
     SSL_KEY: /etc/ssl/manager-2-key.key
     API_USERNAME: ${API_USERNAME}
     API_PASSWORD: ${API_PASSWORD}

    volumes:
      - ./config/certs:/etc/ssl:rw
      - ./data/manager2:/var/ossec/data
    ports:
      - "1516:1515"
      - "55001:55000"
    networks:
      - capstone-network

  # =============================
  # DASHBOARD
  # =============================
  dashboard:
    image: wazuh/wazuh-dashboard:4.13.1
    hostname: dashboard.dashboard
    depends_on:
      - nginx
    environment:
      INDEXER_URL: https://nginx:9200
      WAZUH_API_URL: https://nginx:55000
      DASHBOARD_USERNAME: ${DASHBOARD_USERNAME}
      DASHBOARD_PASSWORD: ${DASHBOARD_PASSWORD}
      SSL_CERTIFICATE_AUTHORITIES: /usr/share/wazuh-dashboard/certs/root-ca.pem
      SSL_CERTIFICATE: /usr/share/wazuh-dashboard/certs/dashboard.pem
      SSL_CERTIFICATE_KEY: /usr/share/wazuh-dashboard/certs/dashboard-key.pem
    volumes:
      - ./config/certs:/usr/share/wazuh-dashboard/certs:rw
    ports:
      - "443:443"
    networks:
      - capstone-network

  # =============================
  # NGINX REVERSE PROXY (HTTPS)
  # =============================
  nginx:
    image: nginx:stable
    hostname: nginx.nginx
    depends_on:
      - indexer-1
      - indexer-2
      - manager-1
      - manager-2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/certs:/etc/nginx/certs:rw
    ports:
      - "9200:9200"  # proxy cho indexer cluster
      - "55002:55000"  # proxy cho manager cluster
    networks:
      - capstone-network

volumes:
  indexer1_data:
  indexer2_data:
  manager1_data:
  manager2_data:

networks:
  capstone-network:
    driver: bridge