nodes:
  # ==========================
  # INDEXERS
  # ==========================
  indexer:
    - name: indexer-1.indexer
      ip: indexer-1.indexer
      node_type: indexer

    - name: indexer-2
      ip: indexer-2.indexer
      node_type: indexer

  # ==========================
  # MANAGERS
  # ==========================
  server:
    - name: manager-1
      ip: manager-1.server
      node_type: master
      
    - name: manager-2
      ip: manager-2.server
      node_type: worker
  # ==========================
  # DASHBOARD
  # ==========================
  dashboard:
    - name: dashboard
      ip: dashboard.dashboard
      node_type: dashboard

  # ==========================
  # NGINX (proxy)
  # ==========================
  other:
    - name: nginx
      ip: nginx.nginx
